    - name: copy pom.xml file to managed server
      copy:
        src: /home/devops/practive/pom.xml
        dest: /home/devops/pom.xml

    - name: update pom.xml
      become: yes
      lineinfile:
       path: /home/devops/pom.xml
       regexp: <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
       line: <project>

    - name: Read an element's attribute values
      community.general.xml:
        path: /home/devops/pom.xml
        xpath: /project/version
        content: text
      register: pom_version

    - name: Set variable with extracted value
      set_fact:
        my_variable: "{{ pom_version.matches[0].version }}"

    - name : display values
      debug:
        var: my_variable

    - name: Download artifact from Nexus repository
      maven_artifact:
        group_id: "{{ group_id }}"
        artifact_id: "{{ artifact_id }}"
        version: "{{my_variable}}"
        repository_url: "http://{{nexus_host}}/repository/demoproject-Release/"
        dest: /home/devops
      vars:
        group_id: "com.example"
        artifact_id: "springboot"
        nexus_host: "35.78.217.218:8081"