     - name: Read an element's attribute values
       community.general.xml:
         path: /home/devops/bar.xml
         xpath: /business/name
         content: text
       register: pom_version

     - name: Set variable with extracted value
       set_fact:
         my_variable: "{{ pom_version.matches[0].name }}"

     - name : display values
       debug:
         var: my_variable


     - name: Download artifact from Nexus repository
       maven_artifact:
         group_id: "{{ group_id }}"
         artifact_id: "{{ artifact_id }}"
         version: "{{my_variable}}"
         repository_url: "http://{{nexus_host}}/repository/demoproject-Release/"
         dest: /home/devops
       vars:
         group_id: "com.example"
         artifact_id: "springboot"
         nexus_host: "35.78.217.218:8081"